#Machine Learning - Regression
##Assignemnt 2
###Rhichard Koh

In [1]:
import pandas as pd

df = pd.read_csv('https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv')

In [2]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_scaled_and_encoded = pd.get_dummies(df, columns=['gear'])
df_scaled_and_encoded[['mpg','hp','wt']] = scaler.fit_transform(df_scaled_and_encoded[['mpg','hp','wt']])
df_scaled_and_encoded = df_scaled_and_encoded[['mpg','hp','wt','gear_3','gear_4','gear_5']]

In [3]:
X = df_scaled_and_encoded.drop(columns=['mpg'])
y = df_scaled_and_encoded['mpg']
HP = df_scaled_and_encoded['hp']
wt = df_scaled_and_encoded['wt']
gear = df_scaled_and_encoded[['gear_3','gear_4','gear_5']]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#sklearn

In [5]:
from sklearn.linear_model import LinearRegression
def sklearn_lm(X,y):
  model = LinearRegression()
  model.fit(X,y)
  return (model.intercept_, model.coef_)

In [6]:
X = df[['gear','hp','wt','am']]
y = df['mpg']

##For HP

In [7]:
sklearn_lm(X['hp'].values.reshape(-1,1),y)

(30.098860539622496, array([-0.06822828]))

##For weight

In [8]:
sklearn_lm(X['wt'].values.reshape(-1,1),y)

(37.28512616734204, array([-5.34447157]))

##For gear

In [9]:
sklearn_lm(X['gear'].values.reshape(-1,1),y)

(5.623333333333342, array([3.92333333]))

##For HP, wt, gear, am

In [10]:
sklearn_lm(X,y)

(32.55625619353512,
 array([ 0.40299281, -0.03837417, -2.79995626,  1.68739402]))

#Normal Equation

In [11]:
import numpy as np
def normal_eq_lm(X,y):
  X_np = X.to_numpy()
  y_np = y.to_numpy()
  ones = np.ones(len(X))
  X_np = np.concatenate((ones[:, np.newaxis], X_np), axis=1)
  Xt = X_np.transpose()
  first_part = np.dot(Xt,X_np)
  first_part = np.linalg.inv(first_part)
  second_part = np.dot(Xt, y_np)
  return np.dot(first_part,second_part)

def normal_eq_lm_single(X,y):
  X_np = X.to_numpy()
  y_np = y.to_numpy()
  ones = np.ones(len(X))
  X_np = np.reshape(X_np,(len(X),1))
  X_np = np.concatenate((ones[:, np.newaxis], X_np), axis=1)
  Xt = X_np.transpose()
  first_part = np.dot(Xt,X_np)
  first_part = np.linalg.inv(first_part)
  second_part = np.dot(Xt, y_np)
  return np.dot(first_part,second_part)

In [12]:
X = df[['gear','hp','wt','am']]
y = df['mpg']

##For Horse Power

In [13]:
normal_eq_lm_single(X['hp'],y)

array([30.09886054, -0.06822828])

##For Weight

In [14]:
normal_eq_lm_single(X['wt'],y)

array([37.28512617, -5.34447157])

##For Gear

In [15]:
normal_eq_lm_single(X['gear'],y)

array([5.62333333, 3.92333333])

##For HP, wt, gear, am

In [16]:
normal_eq_lm(X,y)

array([32.55625619,  0.40299281, -0.03837417, -2.79995626,  1.68739402])

#Gradient Descent

In [17]:
def gd_lm(X, y, Θ, b, alpha=0.01):
  # Θ = 0.0
  # b = 0.0
  derivative_Θ = 0.0
  derivative_b = 0.0
  N = X.shape[0]
  for xi,yi in zip(X,y):
    derivative_Θ += -2*xi*(yi-(Θ*xi+b))
    derivative_b += -2*(yi-(Θ*xi+b))
  Θ = Θ - alpha * (1/N) * derivative_Θ
  b = b - alpha * (1/N) * derivative_b
  return Θ, b

##For Horse Power

In [18]:
w = 0.0
b = 0.0
for epoch in range(1000):
  Θ, b = gd_lm(X['hp'],y,w,b)
  y_hat = Θ * X + b
  MSE = np.divide(np.sum((y - y_hat)**2, axis=0), X.shape[0])
  print(f'{epoch} weight: {Θ} bias: {b}')

0 weight: 52.72668750000001 bias: 0.4018124999999999
1 weight: 51.547870078125 bias: 0.7955887499999998
2 weight: 50.3926290046875 bias: 1.1814894749999998
3 weight: 49.260492752718754 bias: 1.5596721854999998
4 weight: 48.15099922578938 bias: 1.9302912417899998
5 weight: 47.0636955693986 bias: 2.2934979169542
6 weight: 45.99813798613561 bias: 2.649440458615116
7 weight: 44.953891554537904 bias: 2.9982641494428135
8 weight: 43.93053005157215 bias: 3.3401113664539572
9 weight: 42.9276357786657 bias: 3.675121639124878
10 weight: 41.94479939121739 bias: 4.003431706342381
11 weight: 40.98161973151805 bias: 4.325175572215533
12 weight: 40.037703665012685 bias: 4.640484560771223
13 weight: 39.11266591983742 bias: 4.949487369555799
14 weight: 38.20612892956568 bias: 5.252310122164682
15 weight: 37.31772267909936 bias: 5.549076419721389
16 weight: 36.44708455364237 bias: 5.839907391326961
17 weight: 35.59385919069452 bias: 6.124921743500422
18 weight: 34.75769833500564 bias: 6.404235808630413


##For weight

In [19]:
w = 0.0
b = 0.0
for epoch in range(1000):
  Θ, b = gd_lm(X['wt'],y,w,b)
  y_hat = Θ * X + b
  MSE = np.divide(np.sum((y - y_hat)**2, axis=0), X.shape[0])
  print(f'{epoch} weight: {Θ} bias: {b}')

0 weight: 1.1935955 bias: 0.4018124999999999
1 weight: 1.1677408746875007 bias: 0.7955887499999998
2 weight: 1.14240334188125 bias: 1.1814894749999998
3 weight: 1.1175725597311252 bias: 1.5596721854999998
4 weight: 1.0932383932240026 bias: 1.9302912417899998
5 weight: 1.0693909100470225 bias: 2.2934979169542
6 weight: 1.0460203765335818 bias: 2.649440458615116
7 weight: 1.0231172536904103 bias: 2.9982641494428135
8 weight: 1.000672193304102 bias: 3.3401113664539572
9 weight: 0.9786760341255204 bias: 3.675121639124878
10 weight: 0.9571197981305098 bias: 4.003431706342381
11 weight: 0.9359946868553994 bias: 4.325175572215533
12 weight: 0.9152920778057919 bias: 4.640484560771223
13 weight: 0.8950035209371754 bias: 4.949487369555799
14 weight: 0.8751207352059323 bias: 5.252310122164682
15 weight: 0.8556356051893133 bias: 5.549076419721389
16 weight: 0.8365401777730272 bias: 5.839907391326961
17 weight: 0.8178266589050668 bias: 6.124921743500422
18 weight: 0.7994874104144652 bias: 6.4042358

##For gear

In [20]:
w = 0.0
b = 0.0
for epoch in range(1000):
  Θ, b = gd_lm(X['gear'],y,w,b)
  y_hat = Θ * X + b
  MSE = np.divide(np.sum((y - y_hat)**2, axis=0), X.shape[0])
  print(f'{epoch} weight: {Θ} bias: {b}')

0 weight: 1.5230625 bias: 0.4018124999999999
1 weight: 1.4934288281250006 bias: 0.7955887499999998
2 weight: 1.4643878296874997 bias: 1.1814894749999998
3 weight: 1.43592765121875 bias: 1.5596721854999998
4 weight: 1.4080366763193748 bias: 1.9302912417899998
5 weight: 1.3807035209179872 bias: 2.2934979169542
6 weight: 1.3539170286246276 bias: 2.649440458615116
7 weight: 1.3276662661771352 bias: 2.9982641494428135
8 weight: 1.3019405189785922 bias: 3.3401113664539572
9 weight: 1.2767292867240208 bias: 3.675121639124878
10 weight: 1.2520222791145401 bias: 4.003431706342381
11 weight: 1.2278094116572493 bias: 4.325175572215533
12 weight: 1.2040808015491042 bias: 4.640484560771223
13 weight: 1.1808267636431222 bias: 4.949487369555799
14 weight: 1.15803780649526 bias: 5.252310122164682
15 weight: 1.1357046284903547 bias: 5.549076419721389
16 weight: 1.1138181140455476 bias: 5.839907391326961
17 weight: 1.0923693298896369 bias: 6.124921743500422
18 weight: 1.071349521416844 bias: 6.404235808

##For HP, wt, gear, am

In [21]:
def loss(y,hat):
    N = len(y)
    sum = 0
    for i in range(N):
        sum += (y[i]-hat[i])**2
    return (1/N)*sum

In [22]:
def y_hat(w,x,b):
    pred_list = []
    for i in range(len(x)):
        pred_list.append(np.dot(w,x[i])+b)
    return np.array(pred_list)

In [23]:
def dldw(x,y,y_hat):
    sum = 0
    N = len(y)
    for i in range(N):
        sum += -x[i]*(y[i]-y_hat[i])
    return (2/N)*sum

In [24]:
def dldb(y,y_hat):
    N = len(y)
    sum = 0
    for i in range(N):
        sum += -(y[i]-y_hat[i])
    return (2/N) * sum

In [25]:
def gd_lm(x,y, epoch=400, alpha=0.01):
    w = np.random.randn(x.shape[1])
    b = 0
    for i in range(epoch):
        y_predicted = y_hat(w,x,b)
        w = w - alpha *dldw(x,y,y_predicted) 
        b = b - alpha * dldb(y,y_predicted)    
    return w,b

In [26]:
Xscaled = scaler.fit_transform(X)
yscaled = y.values.reshape(-1,1)
yscaled = scaler.fit_transform(yscaled)
w,b=gd_lm(Xscaled,yscaled)

w,b

(array([ 0.62045813, -0.11398043,  0.56598375,  0.20982602]),
 array([-0.12941563]))

Gradient Descent has to be scaled therefore it would not have the exact same weights and biases